### ISSUE TITLE
Ugly glitch with one-hit-kill settings

### ISSUE THREAD

**Issue by suikoden** [openlierox/openlierox#755]
I'm making a one-hit-kill OLX setup. When WormDamageFactor = 1.0, and WormShieldFactor = 0.1, there is no problem.

However, if I set the damage even 0.1 higher, the health bars go haywire. Instead of rainbow-colored overhead bars, they become a circle of dots that constantly circle around the player.

Screenshot: http://postimage.org/image/159zqdtno/

Worse, I can't disable them with the H key. They're permanent. Setting "ShowWormHealth = false" in the MyDocuments options.cfg does nothing either.

for OLX ver 0.58 rc 3

**Comment by pelya** [comment]
That had to be a GFX effect to show that your worm is overpowered and dangerous, when you're picking a certain bonus (this bonus was not implemented), but it somehow messed up - the dots should be white and sparky, not blue and ugly.
The same thing should appear around your worm when it has high shield factor or health, but it will rotate in a different direction.

**Comment by albertz** [comment]
Hey,

The circle of dots are just the marker about the damage factor, not the health bar indicator. It's similar as in e.g. Quake3 or so, there you also have some sort of blue field floating around you when you have Quad Damage (i.e. damage factor = 4).

So that is by purpose. But maybe you are requesting then for an option to disable that?

**Comment by albertz** [comment]
closing this for now ....
