### ISSUE TITLE
Can't compile mods - link to LMS is dead

### ISSUE THREAD

**Issue by Danjb1** [openlierox/openlierox#843]
From the [FAQ](https://www.openlierox.net/faq/):

> I created a mod and when I compile it with Game Compiler it's not working, why?
> The original Game Compiler from Jason Boettcher is broken. Please use [LMS](http://lxalliance.net/forum/index.php?action=mgallery;sa=item;id=5470) instead

The link to LMS is broken - does anyone have a copy?

**Comment by lxkurko** [comment]
Sources seem to be available in tools/GameCompiler but you have to compile them yourself.

**Comment by lxkurko** [comment]
LMS is probably considered obsolete too. There are GameCompiler sources in tools/GameCompiler, you can try that (you have to compile it yourself), it might be more up to date. If it doesn't work, please file a bug.

**Comment by KangaRoo1372** [comment]
Hi @Danjb1, I guess your request might be actually outdated (since you created this issue over 6 months ago), but Iemme provide you some information about LMS and compiling mods.
So, generally olx forum (and thus olx wiki and filebase as well) has been dead for a long time, but fortunately some threads and files can still be accessed with Wayback Archive - including LMS installer, which you can download that way too.
However, I recommend using the GameCompiler instead as lxkurko suggested too. Maybe GC hasn't got any user-friendly interface (you just run it with the cmd line), but I tested it and successfully compiled the mod with it on modern OS (win10 home).
On the other hand, I tried LMS and although I managed to run it on my win10, some options does not work correctly. Especially, I couldn't compile any mod with it (i.e. export my project as a compiled mod; maybe it's an issue only on my side though).
edit: by the way, I made some tests with openlierox v. 0.58 (rc5) and seems like actually you don't need to compile your mod into .lgs file at all to make it work. Seems like the gamescript compiler is now embedded in OLX, which means that the mod will be compiled on the fly and successfully read in-game. All you need to do is just put your uncompiled mod files (txt files) into a separate folder in the game directory.

**Comment by Danjb1** [comment]
Thank you both for the information! 👍
